### ISSUE TITLE
network next_default not found

### ISSUE THREAD

**Issue by alexschroeter** [jhnnsrs/deployer#2]
```
ERROR:rekuest_next.actors.functional:Error in actor
Traceback (most recent call last):
  File "/home/aschroeter/src/apptainer-deployer/arkitekt-next-env/lib/python3.10/site-packages/docker/api/client.py", line 275, in _raise_for_status
    response.raise_for_status()
  File "/home/aschroeter/src/apptainer-deployer/arkitekt-next-env/lib/python3.10/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url:
http+docker://localhost/v1.47/containers/22c97256c4879418373a5e6a94869dd0d2d61b2f3a814ce7c3bb25d071b0476c/start

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/aschroeter/src/apptainer-deployer/arkitekt-next-env/lib/python3.10/site-packages/rekuest_next/actors/functional.py", line 206, in on_assign
    returns = await run_spawned(
  File "/home/aschroeter/src/apptainer-deployer/arkitekt-next-env/lib/python3.10/site-packages/koil/helpers.py", line 218, in run_spawned
    shielded_f = await asyncio.shield(f)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/aschroeter/src/apptainer-deployer/arkitekt-next-env/lib/python3.10/site-packages/koil/helpers.py", line 203, in wrapper
    raise e
  File "/home/aschroeter/src/apptainer-deployer/arkitekt-next-env/lib/python3.10/site-packages/koil/helpers.py", line 200, in wrapper
    return sync_func(**sync_kwargs)
  File "/home/aschroeter/src/deployer/app.py", line 448, in deploy
    container = docker.containers.run(
  File "/home/aschroeter/src/apptainer-deployer/arkitekt-next-env/lib/python3.10/site-packages/docker/models/containers.py", line 883, in run
    container.start()
  File "/home/aschroeter/src/apptainer-deployer/arkitekt-next-env/lib/python3.10/site-packages/docker/models/containers.py", line 420, in start
    return self.client.api.start(self.id, **kwargs)
  File "/home/aschroeter/src/apptainer-deployer/arkitekt-next-env/lib/python3.10/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/home/aschroeter/src/apptainer-deployer/arkitekt-next-env/lib/python3.10/site-packages/docker/api/container.py", line 1136, in start
    self._raise_for_status(res)
  File "/home/aschroeter/src/apptainer-deployer/arkitekt-next-env/lib/python3.10/site-packages/docker/api/client.py", line 277, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
  File "/home/aschroeter/src/apptainer-deployer/arkitekt-next-env/lib/python3.10/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.NotFound: 404 Client Error for http+docker://localhost/v1.47/containers/22c97256c4879418373a5e6a94869dd0d2d61b2f3a814ce7c3bb25d071b0476c/start: Not Found
("network next_default not found")
Error updating pod status Pod matching query does not exist.
```

**Comment by alexschroeter** [comment]
Ah this is the caddy url which is not pointing to the server.

**Comment by alexschroeter** [comment]
Should be addressed in the first commit of this PR https://github.com/jhnnsrs/deployer/pull/3
